import json
import os
from groq import Groq
from pydantic import BaseModel

_groq_client = None


def _get_groq_client() -> Groq:
    global _groq_client
    if _groq_client is None:
        _groq_client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _groq_client


class _ClassifierOutput(BaseModel):
    score: float


def llm_classifier(text: str) -> float:
    """
    Signal 1: LLM Classifier.

    Uses an LLM to evaluate the semantic meaning, tone, and context of the
    submitted text. Returns a confidence score between 0.0 (likely human) and
    1.0 (likely AI-generated).
    """
    system_prompt = (
        "You are an AI-authorship detection classifier. "
        "Analyze the submitted text and return a JSON object with a single key "
        "'score' set to a decimal number between 0.0 and 1.0. "
        "0.0 means you are certain the text was written by a human. "
        "1.0 means you are certain the text was generated by an AI. "
        "Consider tone, semantic coherence, phrasing patterns, and stylistic markers."
    )

    client = _get_groq_client()
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": text},
        ],
        response_format={"type": "json_object"},
        temperature=0,
    )

    raw = response.choices[0].message.content
    parsed = _ClassifierOutput.model_validate(json.loads(raw))
    return parsed.score
